### ISSUE TITLE
OSX - TypeError: hex is not a function stops builder in its tracks.

### ISSUE THREAD

**Issue by Blatman** [evshiron/nwjs-builder-phoenix#57]
OSX 10.11.6  El Capitan

Running nwjs-builder-phoenix will produce the TypeError and the nwjs.app package produced in the dist folder will be incomplete (app.nw is empty). Basically the error is stopping the process before the files can be copied and I also found the renameMacApp would not work.
With a bit of hacking around I managed to get it going OK on both 0.14.7 and 0.23.6
Attached is a test project with the problem and a fresh install of nwjs-builder-phoenix.

My fixes (in Builder.js) were -
//                        encoding = data.indexOf(Buffer.from('43004600', 'hex')) >= 0
//                              ? 'ucs2' : 'utf-8';

if (data.indexOf(new Buffer('43004600', 'hex')) >= 0) {
  encoding = 'ucs2';
} else {
  encoding = 'utf-8';
}

and
//                        return [4 /*yield*/, fs_extra_1.writeFile(path, Buffer.from(newStrings, encoding))];
                        return [4 /*yield*/, fs_extra_1.writeFile(path, Buffer(newStrings, encoding))];

[SimpleProject.zip](https://github.com/evshiron/nwjs-builder-phoenix/files/1117888/SimpleProject.zip)

**Comment by evshiron** [comment]
Could you please post the full log along with your node.js version? I can't reproduce it with node.js 7.7.2.

**Comment by Blatman** [comment]
Didn't have a full log but got this with the SimpleProject -
blatmini:Desktop blatman$ cd SimpleProject
blatmini:SimpleProject blatman$ ls
Info.plist	Resources	node_modules	package.json	src
blatmini:SimpleProject blatman$ npm run dist

> SimpleProject@0.1.0 dist /Users/blatman/Desktop/SimpleProject
> build --mac --x64 --mirror https://dl.nwjs.io/ ./src/

Starting building tasks... { tasks: [ [ 'mac', 'x64' ] ], concurrent: false }
Building for mac, x64 starts...
Fetching NW.js binary... { platform: 'mac', arch: 'x64', version: '0.23.5', flavor: 'sdk' }

[=================================================-] 4562.74KB/s 0.3s

Building targets...
Building directory target starts...
[TypeError: hex is not a function]
Building for mac, x64 ends within 28.44s.
blatmini:SimpleProject blatman$ npm run dist    (good after tweaks)

> SimpleProject@0.1.0 dist /Users/blatman/Desktop/SimpleProject
> build --mac --x64 --mirror https://dl.nwjs.io/ ./src/

Starting building tasks... { tasks: [ [ 'mac', 'x64' ] ], concurrent: false }
Building for mac, x64 starts...
Fetching NW.js binary... { platform: 'mac', arch: 'x64', version: '0.23.5', flavor: 'sdk' }
Building targets...
Building directory target starts...
Building directory target ends within 3.50s.
Building for mac, x64 ends within 3.99s.
blatmini:SimpleProject blatman$ node -v
v4.2.2
blatmini:SimpleProject blatman$ 

0.14.7 runs node 5.12.0
0.23.5 runs node 8.1.2

Had another quick look at the tweaks and found that using Buffer rather than Buffer.from and adjusting the ternary statement to be on one line it works OK.
orig-
316     encoding = data.indexOf(Buffer.from('43004600', 'hex')) >= 0 
317              ? 'ucs2' : 'utf-8';

new-
316     encoding = data.indexOf(new Buffer('43004600', 'hex')) >= 0 ? 'ucs2' : 'utf-8';

Cheers.

**Comment by evshiron** [comment]
Wait a bit. It should work after upgrading your node.js from 4.2.2 to 5.x or later. Changing node.js version should be easy enough by using `n` or `nvm`, and I am going to preserve `Buffer.from` for future compatibility.

However, thanks for the information.

**Comment by Blatman** [comment]
Aye fair enough - I upgraded my system node via nvm (8.1.3) and it works OK.

Thanks
